# Generated by Django 5.1.5 on 2025-01-31 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=10, unique=True)),
                ('course_name', models.CharField(max_length=100)),
                ('credit', models.PositiveIntegerField()),
                ('gpa_value', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
